import { Component, OnInit } from '@angular/core';
import { Chart } from 'chart.js/auto';
 
@Component({
  selector: 'app-pie-chart',
  templateUrl: './pie-chart.component.html',
  styleUrls: ['./pie-chart.component.css']
})
export class PieChartComponent implements OnInit {
 
  constructor() { }
 
  ngOnInit(): void {
    this.createChart();
  }
 
  createChart(): void {
    const employeeData = [
      { name: 'Tim Perkinson', timeWorked: -4 },
      { name: 'Abhay Singh', timeWorked: -4 },
      { name: 'Abhay Singh', timeWorked: -4 },
      { name: 'Mary Poppins', timeWorked: -4 },
      { name: 'Abhay Singh', timeWorked: -3 },
      { name: 'Mary Poppins', timeWorked: -3 },
      { name: 'Mary Poppins', timeWorked: -3 },
      { name: 'Patrick Huthinson', timeWorked: -3 },
      { name: 'Patrick Huthinson', timeWorked: -3 },
      { name: 'John Black', timeWorked: -2 },
      { name: 'Abhay Singh', timeWorked: -2 },
      { name: 'Raju Sunuwar', timeWorked: -2 },
      { name: 'Tim Perkinson', timeWorked: -2 },
      { name: 'Tim Perkinson', timeWorked: -2 },
      { name: 'Kavvay Verma', timeWorked: -2 },
      { name: 'John Black', timeWorked: -1},
      { name: 'Kavvay Verma', timeWorked: -1 },
      { name: 'Abhay Singh', timeWorked: -1 },
      { name: 'Abhay Singh', timeWorked: -1 },
      { name: 'Raju Sunuwar', timeWorked: -1 },
      { name: 'Mary Poppins', timeWorked: 0},
      { name: 'Abhay Singh', timeWorked: 0 },
      { name: 'Patrick Huthinson', timeWorked: 0 },
      { name: 'Patrick Huthinson', timeWorked: 0},
      { name: 'Abhay Singh', timeWorked: 0 },
      { name: 'Mary Poppins', timeWorked: 0 },
      { name: 'Kavvay Verma', timeWorked: 0},
      { name: 'John Black', timeWorked:0 },
      { name: 'Abhay Singh', timeWorked:0 },
      { name: 'Mary Poppins	', timeWorked: 0},
      { name: 'Stewart Malachi0', timeWorked: 0},
      { name: 'John Black', timeWorked:0 },
      { name: 'Patrick Huthinson', timeWorked: 0},
      { name: '', timeWorked: 0},
      { name: 'Rita Alley', timeWorked: 0},
      { name: '', timeWorked: 0},
      { name: 'Rita Alley', timeWorked: 0},
      { name: 'Kavvay Verma', timeWorked: 0},
      { name: 'Patrick Huthinson', timeWorked:0 },
      { name: 'Tamoy Smith', timeWorked:0 },
      { name: 'Rita Alley', timeWorked:0 },
      { name: 'Tim Perkinson', timeWorked: 0},
      { name: 'Tim Perkinson', timeWorked: 0},
      { name: 'Patrick Huthinson', timeWorked:0 },
      { name: 'Patrick Huthinson', timeWorked:0 },
      { name: 'Tim Perkinson', timeWorked:0 },
      { name: 'John Black', timeWorked:0 },
      { name: 'John Black', timeWorked: 0},
      { name: 'Abhay Singh', timeWorked:0 },
      { name: 'Abhay Singh', timeWorked:0 },
      { name: 'Patrick Huthinson', timeWorked: 0},
      { name: 'Rita Alley', timeWorked:0 },
      { name: 'Patrick Huthinson', timeWorked:0 },
      { name: 'Tamoy Smith', timeWorked:0 },
      { name: 'Mary Poppins', timeWorked:0 },
      { name: 'Abhay Singh', timeWorked:0 },
      { name: 'Mary Poppins', timeWorked: 0},
      { name: 'Mary Poppins', timeWorked: 0},
      { name: 'Tamoy Smith', timeWorked: 0},
      { name: 'Abhay Singh', timeWorked: 0},
      { name: 'Mary Poppins', timeWorked: 0},
      { name: 'Raju Sunuwar', timeWorked: 0},
      { name: 'Mary Poppins', timeWorked: 0},
      { name: 'Kavvay Verma', timeWorked: 0},
      { name: 'Tamoy Smith', timeWorked: 0},
      { name: 'John Black', timeWorked: 0},
      { name: 'Stewart Malachi', timeWorked: 0},
      { name: 'Stewart Malachi', timeWorked: 0},
      { name: 'Mary Poppins', timeWorked: 0},
      { name: 'Stewart Malachi', timeWorked: 0},
      { name: 'Mary Poppins', timeWorked: 0},
      { name: 'Stewart Malachi', timeWorked: 0},
      { name: 'Patrick Huthinson', timeWorked: 0},
      { name: 'Stewart Malachi', timeWorked: 0},
      { name: 'John Black', timeWorked: 0},
      { name: 'Stewart Malachi', timeWorked: 0},
      { name: 'Kavvay Verma', timeWorked: 0},
      { name: 'Stewart Malachi', timeWorked: 0},
      { name: 'Abhay Singh', timeWorked: 0},
      { name: 'Abhay Singh', timeWorked: 0},
      { name: '', timeWorked: 0},
      { name: 'Mary Poppins', timeWorked: 0},
      { name: 'Abhay Singh', timeWorked: 0},
      { name: 'Tim Perkinson', timeWorked: 0},
      { name: 'Abhay Singh', timeWorked: 0},
      { name: 'Patrick Huthinson', timeWorked: 0},
      { name: 'Tim Perkinson', timeWorked: 0},
      { name: 'Tim Perkinson', timeWorked: 0},
      { name: 'Kavvay Verma', timeWorked: 0},
      { name: 'Tamoy Smith', timeWorked: 0},
      { name: 'John Black', timeWorked: 0},
      { name: 'Patrick Huthinson', timeWorked: 0},
      { name: 'John Black', timeWorked: 0},
      { name: 'Kavvay Verma', timeWorked: 0},
      { name: 'Tim Perkinson', timeWorked: 0},
      { name: 'Raju Sunuwar', timeWorked: 0},
      { name: 'Abhay Singh', timeWorked: 0},
      { name: 'Rita Alley', timeWorked: 0},
      { name: 'Stewart Malachi', timeWorked: 0},
      { name: 'Mary Poppins', timeWorked: 0},
      { name: 'Patrick Huthinson', timeWorked: 0},
      { name: 'Patrick Huthinson', timeWorked: 0},
      { name: 'Mary Poppins', timeWorked: 0},
      { name: 'Patrick Huthinson', timeWorked: 0},
      { name: 'Patrick Huthinson', timeWorked: 0},
      { name: 'Patrick Huthinson', timeWorked: 0},
      { name: 'Kavvay Verma', timeWorked: 0},
      { name: 'Abhay Singh', timeWorked: 0},
      { name: 'John Black', timeWorked: 0},
      { name: 'Stewart Malachi', timeWorked: 0},
      { name: 'John Black', timeWorked: 0},
      { name: 'Stewart Malachi', timeWorked: 0},
      { name: 'Stewart Malachi', timeWorked: 0},
      { name: 'Raju Sunuwar', timeWorked: 0},
      { name: 'Abhay Singh', timeWorked: 0},
      { name: 'Tim Perkinson', timeWorked: 0},
      { name: 'Abhay Singh', timeWorked: 0},
      { name: 'John Black', timeWorked: 0},
      { name: 'Stewart Malachi', timeWorked: 0},
      { name: 'Stewart Malachi', timeWorked: 0},
      { name: 'Tamoy Smith', timeWorked: 0},
      { name: 'Tim Perkinson', timeWorked: 0},
      { name: 'John Black', timeWorked: 0},
      { name: 'Raju Sunuwar', timeWorked: 0},
      { name: 'John Black', timeWorked: 0},
      { name: 'John Black', timeWorked: 0},
      { name: 'Abhay Singh', timeWorked: 0},
      { name: 'John Black', timeWorked: 0},
      { name: 'John Black', timeWorked: 0},
      { name: 'Rita Alley', timeWorked: 0},
      { name: 'Tim Perkinson', timeWorked: 0},
      { name: 'Tamoy Smith', timeWorked: 0},
      { name: 'Kavvay Verma', timeWorked: 0},
      { name: 'John Black', timeWorked: 0},
      { name: 'Tim Perkinsond',timeWorked: 0},
      { name: 'Tim Perkinson', timeWorked: 0},
      { name: 'John Black', timeWorked: 0},
      { name: 'Rita Alley', timeWorked: 0},
      { name: 'Tamoy Smith', timeWorked: 0},
      { name: 'Mary Poppins', timeWorked: 0},
      { name: 'Stewart Malachi', timeWorked: 0},
      { name: 'Raju Sunuwar', timeWorked: 0},
      { name: 'Patrick Huthinson', timeWorked: 0},
      { name: 'Abhay Singh', timeWorked: 0},
      { name: 'Tamoy Smith', timeWorked: 0},
      { name: 'John Black', timeWorked: 0},
      { name: 'Rita Alley', timeWorked: 0},
      { name: 'Stewart Malachi', timeWorked: 0},
      { name: 'Tim Perkinson', timeWorked: 0},
      { name: 'Mary Poppins', timeWorked: 0},
      { name: 'Tamoy Smith', timeWorked: 0},
      { name: 'Kavvay Verma', timeWorked: 0},
      { name: 'Stewart Malachi', timeWorked: 0},
      { name: 'Patrick Huthinson', timeWorked: 0},
      { name: 'Patrick Huthinson', timeWorked: 0},
      { name: 'Kavvay Verma', timeWorked: 0},
      { name: 'Mary Poppins', timeWorked: 0},
      { name: 'Mary Poppins', timeWorked: 0},
      { name: 'Patrick Huthinson', timeWorked: 0},
      { name: 'Raju Sunuwar', timeWorked: 0},
      { name: 'John Black', timeWorked: 0},
      { name: 'John Black', timeWorked: 0},
      { name: 'Tamoy Smith', timeWorked: 0},
      { name: 'John Black', timeWorked: 0},
      { name: 'Raju Sunuwar', timeWorked: 0},
      { name: 'Patrick Huthinson', timeWorked: 0},
      { name: 'Patrick Huthinson', timeWorked: 0},
      { name: 'Kavvay Verma', timeWorked: 0},
      { name: 'Kavvay Verma', timeWorked: 0},
      { name: 'Abhay Singh', timeWorked: 0},
      { name: 'Rita Alley', timeWorked: 0},
      { name: 'Kavvay Verma', timeWorked: 0},
      { name: 'John Black', timeWorked: 0},
      { name: 'Raju Sunuwar', timeWorked: 0},
      { name: 'Tim Perkinson', timeWorked: 0},
      { name: 'Tim Perkinson', timeWorked: 0},
      { name: 'Stewart Malachi', timeWorked: 0},
      { name: 'Rita Alley', timeWorked: 0},
      { name: 'Rita Alley', timeWorked: 0},
      { name: 'Abhay Singh', timeWorked: 0},
      { name: 'Tim Perkinson', timeWorked: 0},
      { name: 'Abhay Singh', timeWorked: 0},
      { name: 'Mary Poppins', timeWorked: 0},
      { name: 'Abhay Singh', timeWorked: 0},
      { name: 'Abhay Singh', timeWorked: 0},
      { name: 'Tamoy Smith', timeWorked: 0},
      { name: 'Tamoy Smith', timeWorked: 0},
      { name: 'Patrick Huthinson', timeWorked: 0},
      { name: 'Raju Sunuwar', timeWorked: 0},
      { name: 'Tamoy Smith', timeWorked: 0},
      { name: 'John Black', timeWorked: 0},
      { name: 'Kavvay Verma', timeWorked: 0},
      { name: 'Mary Poppins', timeWorked: 0},
      { name: 'Kavvay Verma', timeWorked: 0},
      { name: 'Abhay Singh', timeWorked: 0},
      { name: 'Abhay Singh', timeWorked: 1},
      { name: 'Kavvay Verma', timeWorked: 1},
      { name: 'Rita Alley', timeWorked: 1},
      { name: 'John Black', timeWorked: 1},
      { name: 'Mary Poppins', timeWorked: 1},
      { name: 'Rita Alley', timeWorked: 1},
      { name: 'Raju Sunuwar', timeWorked: 1},
      { name: 'Tamoy Smith', timeWorked: 1},
      { name: 'John Black', timeWorked: 1},
      { name: 'Tim Perkinson', timeWorked: 1},
      { name: 'Mary Poppins', timeWorked: 1},
      { name: 'John Black', timeWorked: 1},
      { name: 'Stewart Malachi', timeWorked: 1},
      { name: 'Patrick Huthinson', timeWorked: 1},
      { name: 'Mary Poppins', timeWorked: 1},
      { name: 'Patrick Huthinson', timeWorked: 1},
      { name: 'Stewart Malachi', timeWorked: 1},
      { name: 'Abhay Singh', timeWorked: 1},
      { name: 'Patrick Huthinson', timeWorked: 1},
      { name: 'Abhay Singh', timeWorked: 1},
      { name: 'Stewart Malachi', timeWorked: 1},
      { name: 'Abhay Singh', timeWorked: 1},
      { name: 'Stewart Malachi', timeWorked: 1},
      { name: 'Tamoy Smith', timeWorked: 1},
      { name: 'Kavvay Verma', timeWorked: 1},
      { name: 'Kavvay Verma', timeWorked: 1},
      { name: 'John Black', timeWorked: 1},
      { name: 'Mary Poppins', timeWorked: 1},
      { name: 'Rita Alley', timeWorked: 1},
      { name: 'Tim Perkinson', timeWorked: 1},
      { name: 'Stewart Malachi', timeWorked: 1},
      { name: 'Kavvay Verma', timeWorked: 1},
      { name: 'Abhay Singh', timeWorked: 1},
      { name: 'Kavvay Verma', timeWorked: 1},
      { name: 'John Black', timeWorked: 1},
      { name: 'Patrick Huthinson', timeWorked: 1},
      { name: 'Kavvay Verma', timeWorked: 1},
      { name: 'Rita Alley', timeWorked: 1},
      { name: 'Tim Perkinson', timeWorked: 1},
      { name: 'Mary Poppins', timeWorked: 1},
      { name: 'Tim Perkinson', timeWorked: 1},
      { name: 'Kavvay Verma', timeWorked: 1},
      { name: 'Rita Alley', timeWorked: 1},
      { name: 'Mary Poppins', timeWorked: 1},
      { name: 'Abhay Singh', timeWorked: 1},
      { name: 'Stewart Malachi', timeWorked: 1},
      { name: 'John Black', timeWorked: 1},
      { name: 'Stewart Malachi', timeWorked: 1},
      { name: 'Abhay Singh', timeWorked: 1},
      { name: 'John Black', timeWorked: 1},
      { name: 'Rita Alley', timeWorked: 1},
      { name: 'John Black', timeWorked: 1},
      { name: 'Tim Perkinson', timeWorked: 1},
      { name: 'Stewart Malachi', timeWorked: 1},
      { name: 'John Black', timeWorked: 1},
      { name: 'John Black', timeWorked: 1},
      { name: 'John Black', timeWorked: 1},
      { name: 'Kavvay Verma', timeWorked: 1},
      { name: 'Kavvay Verma', timeWorked: 1},
      { name: 'Stewart Malachi', timeWorked: 1},
      { name: 'Abhay Singh', timeWorked: 1},
      { name: 'Abhay Singh', timeWorked: 1},
      { name: 'Tim Perkinson', timeWorked: 1},
      { name: 'Abhay Singh', timeWorked: 1},
      { name: 'Patrick Huthinson', timeWorked: 1},
      { name: 'Patrick Huthinson', timeWorked: 1},
      { name: 'Stewart Malachi', timeWorked: 1},
      { name: 'Tim Perkinson', timeWorked: 1},
      { name: 'Tamoy Smith', timeWorked: 1},
      { name: 'Raju Sunuwar', timeWorked: 1},
      { name: 'Patrick Huthinson', timeWorked: 1},
      { name: 'Mary Poppins', timeWorked: 1},
      { name: 'Patrick Huthinson', timeWorked: 1},
      { name: 'Kavvay Verma', timeWorked: 1},
      { name: '', timeWorked: 1},
      { name: 'Tim Perkinson', timeWorked: 1},
      { name: 'Patrick Huthinson', timeWorked: 1},
      { name: 'Tim Perkinson', timeWorked: 1},
      { name: 'Patrick Huthinson', timeWorked: 2},
      { name: 'Abhay Singh', timeWorked: 2},
      { name: 'Raju Sunuwar', timeWorked: 2},
      { name: 'Raju Sunuwar', timeWorked: 2},
      { name: 'Stewart Malachi', timeWorked: 2},
      { name: 'Rita Alley', timeWorked: 2},
      { name: 'Mary Poppins', timeWorked: 2},
      { name: 'Patrick Huthinson', timeWorked: 2},
      { name: 'Tim Perkinson', timeWorked: 2},
      { name: 'Stewart Malachi', timeWorked: 2},
      { name: 'Patrick Huthinson', timeWorked: 2},
      { name: 'Mary Poppins', timeWorked: 2},
      { name: 'Tamoy Smith', timeWorked: 2},
      { name: 'Tim Perkinson', timeWorked: 2},
      { name: 'Rita Alley', timeWorked: 2},
      { name: 'Stewart Malachi', timeWorked: 2},
      { name: '', timeWorked: 2},
      { name: 'Abhay Singh', timeWorked: 2},
      { name: 'Tim Perkinson', timeWorked: 2},
      { name: 'Tim Perkinson', timeWorked: 2},
      { name: 'Tim Perkinson', timeWorked: 2},
      { name: 'Abhay Singh', timeWorked: 2},
      { name: 'Stewart Malachi', timeWorked: 2},
      { name: 'Stewart Malachi', timeWorked: 2},
      { name: 'Abhay Singh', timeWorked: 2},
      { name: '', timeWorked: 2},
      { name: 'Stewart Malachi', timeWorked: 2},
      { name: 'Stewart Malachi', timeWorked: 2},
      { name: 'Tamoy Smith', timeWorked: 2},
      { name: 'Kavvay Verma', timeWorked: 2},
      { name: 'Kavvay Verma', timeWorked: 2},
      { name: 'Patrick Huthinson', timeWorked: 2},
      { name: 'Kavvay Verma', timeWorked: 2},
      { name: 'Tim Perkinson', timeWorked: 2},
      { name: 'Patrick Huthinson', timeWorked: 2},
      { name: 'Stewart Malachi', timeWorked: 2},
      { name: 'Abhay Singh', timeWorked: 2},
      { name: 'Patrick Huthinson', timeWorked: 2},
      { name: 'Stewart Malachi', timeWorked: 2},
      { name: 'Tim Perkinson', timeWorked: 2},
      { name: 'Abhay Singh', timeWorked: 2},
      { name: 'Stewart Malachi', timeWorked: 2},
      { name: 'Rita Alley', timeWorked: 2},
      { name: 'Kavvay Verma', timeWorked: 2},
      { name: 'Rita Alley', timeWorked: 2},
      { name: 'John Black', timeWorked: 2},
      { name: 'Patrick Huthinson', timeWorked: 2},
      { name: 'Kavvay Verma', timeWorked: 2},
      { name: 'Tamoy Smith', timeWorked: 2},
      { name: 'Mary Poppins', timeWorked: 2},
      { name: 'John Black', timeWorked: 2},
      { name: 'Rita Alley', timeWorked: 2},
      { name: 'Patrick Huthinson', timeWorked: 2},
      { name: 'Kavvay Verma', timeWorked: 2},
      { name: 'Tim Perkinson', timeWorked: 2},
      { name: '', timeWorked: 2},
      { name: 'Tim Perkinson', timeWorked: 2},
      { name: 'Tamoy Smith', timeWorked: 2},
      { name: 'Kavvay Verma', timeWorked: 2},
      { name: 'Stewart Malachi', timeWorked: 2},
      { name: 'Rita Alley', timeWorked: 2},
      { name: 'Rita Alley', timeWorked: 2},
      { name: 'Raju Sunuwar', timeWorked: 2},
      { name: 'Tim Perkinson', timeWorked: 2},
      { name: 'Mary Poppins', timeWorked: 2},
      { name: 'Abhay Singh', timeWorked: 2},
      { name: '', timeWorked: 2},
      { name: 'Patrick Huthinson', timeWorked: 2},
      { name: 'Tamoy Smith', timeWorked: 3},
      { name: 'Mary Poppins', timeWorked: 3},
      { name: 'John Black', timeWorked: 3},
      { name: 'Tim Perkinson', timeWorked: 3},
      { name: 'Tim Perkinson', timeWorked: 3},
      { name: 'Patrick Huthinson', timeWorked: 3},
      { name: 'Kavvay Verma', timeWorked: 3},
      { name: 'Tim Perkinson', timeWorked: 3},
      { name: 'Patrick Huthinson', timeWorked: 3},
      { name: 'Abhay Singh', timeWorked: 3},
      { name: 'Stewart Malachi', timeWorked: 3},
      { name: 'Raju Sunuwar', timeWorked: 3},
      { name: 'Abhay Singh', timeWorked: 3},
      { name: 'Stewart Malachi', timeWorked: 3},
      { name: 'Abhay Singh', timeWorked: 3},
      { name: 'Patrick Huthinson', timeWorked: 3},
      { name: 'Abhay Singh', timeWorked: 3},
      { name: 'Mary Poppins', timeWorked: 3},
      { name: 'Stewart Malachi', timeWorked: 3},
      { name: 'Rita Alley', timeWorked: 3},
      { name: 'Mary Poppins', timeWorked: 3},
      { name: 'Abhay Singh', timeWorked: 3},
      { name: 'Tim Perkinson', timeWorked: 3},
      { name: 'Kavvay Verma', timeWorked: 3},
      { name: 'Stewart Malachi', timeWorked: 3},
      { name: 'Patrick Huthinson', timeWorked: 3},
      { name: 'Raju Sunuwar', timeWorked: 3},
      { name: 'Abhay Singh', timeWorked: 3},
      { name: 'Raju Sunuwar', timeWorked: 3},
      { name: 'John Black', timeWorked: 3},
      { name: 'Stewart Malachi', timeWorked: 3},
      { name: 'Stewart Malachi', timeWorked: 3},
      { name: 'Mary Poppins', timeWorked: 3},
      { name: 'John Black', timeWorked: 3},
      { name: 'Stewart Malachi', timeWorked: 3},
      { name: 'John Black', timeWorked: 3},
      { name: 'Tamoy Smith', timeWorked: 3},
      { name: 'Rita Alley', timeWorked: 3},
      { name: 'Raju Sunuwar', timeWorked: 3},
      { name: 'Patrick Huthinson', timeWorked: 3},
      { name: 'Tamoy Smith', timeWorked: 3},
      { name: 'Abhay Singh', timeWorked: 3},
      { name: 'Tim Perkinson', timeWorked: 3},
      { name: 'Patrick Huthinson', timeWorked: 3},
      { name: 'Mary Poppins', timeWorked: 3},
      { name: 'John Black', timeWorked: 3},
      { name: 'Patrick Huthinson', timeWorked: 3},
      { name: 'John Black', timeWorked: 3},
      { name: 'John Black', timeWorked: 3},
      { name: 'Raju Sunuwar', timeWorked: 3},
      { name: 'Rita Alley', timeWorked: 3},
      { name: 'John Black', timeWorked: 3},
      { name: 'Abhay Singh', timeWorked: 3},
      { name: 'Mary Poppins', timeWorked: 3},
      { name: 'Abhay Singh', timeWorked: 3},
      { name: 'Patrick Huthinson', timeWorked: 3},
      { name: 'Mary Poppins', timeWorked: 3},
      { name: 'John Black', timeWorked: 3},
      { name: 'Kavvay Verma', timeWorked: 3},
      { name: 'Tim Perkinson', timeWorked: 3},


    ];
 
    const totalTime = employeeData.reduce((sum, employee) => sum + employee.timeWorked, 0);
 
    const chartData = {
      labels: employeeData.map(employee => employee.name),
      datasets: [{
        data: employeeData.map(employee => (employee.timeWorked / totalTime) * 100),
        backgroundColor: ['#FF6384', '#36A2EB', '#FFCE56', '#4BC0C0'],
      }]
    };
 
    const ctx = document.getElementById('timeWorkedChart') as HTMLCanvasElement;
    new Chart(ctx, {
      type: 'pie',
      data: chartData,
      options: {
        responsive: true,
        plugins: {
          tooltip: {
            callbacks: {
              label: function(context) {
                const percentage = context.raw as number; // Cast context.raw to number
                return context.label + ': ' + percentage.toFixed(2) + '%';
              }
            }
          }
        }
      }
    });
  }
}